fastlane_version "1.101.0"

default_platform :ios

  desc "Increment the framework's build number without committing the changes. Returns a string of the new, bumped version."
  lane :bump do |options|
    # Only bump from master branch
    ensure_git_branch()

    # Update build number
    commit_count = sh("git rev-list --count HEAD")

    opt_build_num = options[:build_number] || commit_count
    increment_build_number(build_number: opt_build_num.to_i)

    opt_build_version = options[:version_number]
    if opt_build_version thent
      increment_version_number(version_number: opt_build_version)
    else
      increment_version_number(bump_type: "patch")
    end

    message = "🍻 Version Bump to #{get_version_number}(#{get_build_number})"
    commit_version_bump(
      message: message,
      xcodeproj: "Torch.xcodeproj"
      )

    add_git_tag(
      grouping: "fastlane",
      build_number: "#{get_version_number}(#{get_build_number})"
    )
  end
end